#ifndef COMMON_H
#define COMMON_H

enum {
    // Client->Server
    NET_MSG_TYPE_ACCOUNT_REGIST_REQUEST = 0x0000,
    NET_MSG_TYPE_ACCOUNT_LOGIN_REQUEST = 0x0001,
    NET_MSG_TYPE_ACCOUNT_UPDATE_REQUEST = 0x0002,
    NET_MSG_TYPE_SEND_MESSAGE_REQUEST = 0x0010,
    NET_MSG_TYPE_ADD_FRIEND_REQUEST = 0x0021,
    NET_MSG_TYPE_UPDATE_FRIEND_LIST_REQUEST = 0x0022,
    NET_MSG_TYPE_UPDATE_FRIEND_INFO_REQUEST = 0x0023,
    NET_MSG_TYPE_DELETE_FRIEND_REQUEST = 0x0024,

    NET_MSG_TYPE_HEARTBEAT_REQUEST = 0x00F0,

    // Server->Client
    NET_MSG_TYPE_ACCOUNT_REGIST_RESPONSE = 0x1000,
    NET_MSG_TYPE_ACCOUNT_LOGIN_RESPONSE = 0x1001,
    NET_MSG_TYPE_ACCOUNT_UPDATE_RESPONSE = 0x1002,
    NET_MSG_TYPE_SEND_MESSAGE_RESPONSE = 0x1010,
    NET_MSG_TYPE_ADD_FRIEND_RESPONSE = 0x1021,
    NET_MSG_TYPE_UPDATE_FRIEND_LIST_RESPOSE = 0x1022,
    NET_MSG_TYPE_UPDATE_FRIEND_INFO_RESPONSE = 0x1023,
    NET_MSG_TYPE_DELETE_FRIEND_RESPONSE = 0x1025,

    NET_MSG_TYPE_ADD_FRIEND_PUSH = 0x1024,
    NET_MSG_TYPE_ONLINE_INFO_PUSH = 0x1030,
    NET_MSG_TYPE_UPDATE_FRIEND_INFO_PUSH = 0x1031,
    NET_MSG_TYPE_DELETE_FRIEND_PUSH = 0x1032,

    NET_MSG_TYPE_HEARTBEAT_RESPONSE = 0x10F0
};



#endif // COMMON_H
